POST http://localhost:3000/registro
Content-Type: application/json

{
        "id": 2,
        "nombre":"b",
        "apellido":"b",
        "correo": "b@b",
        "password":"b"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
        "correo": "a@a",
        "password":"123"
}