POST http://localhost:3000/registro
Content-Type: application/json

{
        "id": 2,
        "nombre":"b",
        "apellido":"b",
        "correo": "b@b",
        "password":"b"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
        "id": 1,
        "correo": "a@a",
        "password":"a"
}

###

GET http://localhost:3000/usuario
Content-Type: application/json

###
GET http://localhost:3000/favoritas
Content-Type: application/json

###
POST http://localhost:3000/registro_mascotas
Content-Type: application/json

{
    "id": 2,
    "nombre": "Sasha",
    "especie": "perro",
    "descripcion": "Me gusta jugar",
    "sexo": "Hembra",
    "cumpleaños": "23/09/2007",
    "ubicacion": "Guadalajara",
    "url1":"https://www.24petwatch.com/Portals/24petwatchv2/EasyDNNnews/302/title-img.png",
    "url2":"https://www.24petwatch.com/Portals/24petwatchv2/EasyDNNnews/297/holiday-food-safety-header-img-300x300-2.png",
    "url3":"https://img.clipartlook.com/cute-dog-clipart-clipart-panda-free-clipart-images-clip-art-pets-300_300.jpg"
}

###

DELETE http://localhost:3000/EliminarMascota/1
Content-Type: application/json


###
POST http://localhost:3000/api/users
Content-Type: application/json

{      
        "nombre": "Stringy",
        "apellido":"Stringy",
        "correo": "Stringy",
        "password":"Stringy"
}

###
POST http://localhost:3000/api/login
Content-Type: application/json

{      
        "correo": "Stringe",
        "password":"Stringe"
}
###
GET http://localhost:3000/15
Content-Type: application/json

###
POST http://localhost:3000/api/mascotas
Content-Type: application/json

{
        "nombre":"rufuslocus",
        "especie":"3",
        "descripcion":"loc",
        "sexo":"M",
        "cumpleaños":"12/12/2020",
        "ubicacion":"Guadalajara",
        "url1":"https://www.mutkut.com/wp-content/uploads/2015/12/Loving-You-White-Dog-Display-Picture-300x300.jpg",
        "url2":"https://dogtowndogtraining.com/wp-content/uploads/2012/06/300x300-061-e1340955308953.jpg",
        "url3":"https://www.snazzyjazzypet.com/blog/wp-content/uploads/2012/05/Vineyard-Vines-By-Mascot-Whale-Collar-on-Dog-300x300.jpg",
        "token_usr":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb3JyZW8iOiJxQHEiLCJpYXQiOjE1ODkwODA3MzR9.hif8apBN-tKSruHjt-l2gRImgBgv8BYoC0ySW5ZF8z0"
    }